## One Hot Encoding

In [96]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [97]:
df = pd.read_csv("https://raw.githubusercontent.com/siddiquiamir/Python-Data-Preprocessing/main/data.csv", index_col=0)
df

Colour Country
Id                
1      Red     USA
2     Blue      UK
3    Green  Canada
4     Blue     USA
5     Blue     USA
..     ...     ...
296    Red  Canada
297  Green      UK
298  Green      UK
299    Red  Canada
300    Red  Canada

[300 rows x 2 columns]

In [98]:
df.dtypes

Colour     object
Country    object
dtype: object

In [99]:
df.dtypes

Colour     object
Country    object
dtype: object

In [100]:
df["Colour"].unique()
df["Country"].unique()

array(['USA', 'UK', 'Canada'], dtype=object)

In [101]:
ohe = OneHotEncoder()

In [102]:
ohe.fit_transform(df[["Colour", "Country"]]).toarray()

array([[0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.]])

In [103]:
feature_arry = ohe.fit_transform(df[["Colour", "Country"]]).toarray()

In [104]:
feature_arry

array([[0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.]])

In [105]:
ohe.categories_

[array(['Blue', 'Green', 'Red'], dtype=object),
 array(['Canada', 'UK', 'USA'], dtype=object)]

In [106]:
feature_lables = ohe.categories_
np.array(feature_lables).ravel()
feature_lables = np.array(feature_lables).ravel()

In [107]:
print(feature_lables)

['Blue' 'Green' 'Red' 'Canada' 'UK' 'USA']


In [108]:
print(feature_array)

[[0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 ...
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]


In [109]:
pd.DataFrame(feature_array, columns = feature_lables)

Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     1.0    0.0  0.0     0.0  1.0  0.0
2     0.0    1.0  0.0     1.0  0.0  0.0
3     1.0    0.0  0.0     0.0  0.0  1.0
4     1.0    0.0  0.0     0.0  0.0  1.0
..    ...    ...  ...     ...  ...  ...
295   0.0    0.0  1.0     1.0  0.0  0.0
296   0.0    1.0  0.0     0.0  1.0  0.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    0.0  1.0     1.0  0.0  0.0
299   0.0    0.0  1.0     1.0  0.0  0.0

[300 rows x 6 columns]

In [110]:
print(feature_lables)

['Blue' 'Green' 'Red' 'Canada' 'UK' 'USA']


In [111]:
pd.DataFrame(feature_arry, columns = feature_lables)

Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     1.0    0.0  0.0     0.0  1.0  0.0
2     0.0    1.0  0.0     1.0  0.0  0.0
3     1.0    0.0  0.0     0.0  0.0  1.0
4     1.0    0.0  0.0     0.0  0.0  1.0
..    ...    ...  ...     ...  ...  ...
295   0.0    0.0  1.0     1.0  0.0  0.0
296   0.0    1.0  0.0     0.0  1.0  0.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    0.0  1.0     1.0  0.0  0.0
299   0.0    0.0  1.0     1.0  0.0  0.0

[300 rows x 6 columns]

In [112]:
features = pd.DataFrame(feature_arry, columns = feature_lables)

In [113]:
print(features)

     Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     1.0    0.0  0.0     0.0  1.0  0.0
2     0.0    1.0  0.0     1.0  0.0  0.0
3     1.0    0.0  0.0     0.0  0.0  1.0
4     1.0    0.0  0.0     0.0  0.0  1.0
..    ...    ...  ...     ...  ...  ...
295   0.0    0.0  1.0     1.0  0.0  0.0
296   0.0    1.0  0.0     0.0  1.0  0.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    0.0  1.0     1.0  0.0  0.0
299   0.0    0.0  1.0     1.0  0.0  0.0

[300 rows x 6 columns]


In [114]:
features

Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     1.0    0.0  0.0     0.0  1.0  0.0
2     0.0    1.0  0.0     1.0  0.0  0.0
3     1.0    0.0  0.0     0.0  0.0  1.0
4     1.0    0.0  0.0     0.0  0.0  1.0
..    ...    ...  ...     ...  ...  ...
295   0.0    0.0  1.0     1.0  0.0  0.0
296   0.0    1.0  0.0     0.0  1.0  0.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    0.0  1.0     1.0  0.0  0.0
299   0.0    0.0  1.0     1.0  0.0  0.0

[300 rows x 6 columns]

In [115]:
pd.concat([df, features], axis=1)

Colour Country  Blue  Green  Red  Canada   UK  USA
1      Red     USA   1.0    0.0  0.0     0.0  1.0  0.0
2     Blue      UK   0.0    1.0  0.0     1.0  0.0  0.0
3    Green  Canada   1.0    0.0  0.0     0.0  0.0  1.0
4     Blue     USA   1.0    0.0  0.0     0.0  0.0  1.0
5     Blue     USA   0.0    0.0  1.0     1.0  0.0  0.0
..     ...     ...   ...    ...  ...     ...  ...  ...
297  Green      UK   0.0    1.0  0.0     0.0  1.0  0.0
298  Green      UK   0.0    0.0  1.0     1.0  0.0  0.0
299    Red  Canada   0.0    0.0  1.0     1.0  0.0  0.0
300    Red  Canada   NaN    NaN  NaN     NaN  NaN  NaN
0      NaN     NaN   0.0    0.0  1.0     0.0  0.0  1.0

[301 rows x 8 columns]

In [116]:
df_new = pd.concat([df, features], axis=1)

In [117]:
df_new

Colour Country  Blue  Green  Red  Canada   UK  USA
1      Red     USA   1.0    0.0  0.0     0.0  1.0  0.0
2     Blue      UK   0.0    1.0  0.0     1.0  0.0  0.0
3    Green  Canada   1.0    0.0  0.0     0.0  0.0  1.0
4     Blue     USA   1.0    0.0  0.0     0.0  0.0  1.0
5     Blue     USA   0.0    0.0  1.0     1.0  0.0  0.0
..     ...     ...   ...    ...  ...     ...  ...  ...
297  Green      UK   0.0    1.0  0.0     0.0  1.0  0.0
298  Green      UK   0.0    0.0  1.0     1.0  0.0  0.0
299    Red  Canada   0.0    0.0  1.0     1.0  0.0  0.0
300    Red  Canada   NaN    NaN  NaN     NaN  NaN  NaN
0      NaN     NaN   0.0    0.0  1.0     0.0  0.0  1.0

[301 rows x 8 columns]